# Generated by Django 4.1.1 on 2022-09-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.pedido')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produto.produto')),
            ],
        ),
    ]
