# Generated by Django 4.1.1 on 2022-09-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('telefone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefone', to='fornecedor.fornecedor'),
        ),
    ]
