# Generated by Django 4.1.1 on 2022-09-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now=True, verbose_name=())),
                ('nota_fiscal', models.CharField(max_length=255)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='transportadora.transportadora')),
            ],
        ),
    ]
